# Generated by Django 5.0.6 on 2024-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BookingDate',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='No_of_guest',
            new_name='no_of_guest',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='Inventory',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='inventory',
            field=models.SmallIntegerField(default=0),
        ),
    ]
